# Generated by Django 2.1.5 on 2023-10-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20231025_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Placed', 'Placed'), ('Acknowledged', 'Acknowledged'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched'), ('Paused', 'Paused'), ('Paused for 15 Minutes', 'Paused for 15 Minutes'), ('Paused for 30 Minutes', 'Paused for 30 Minutes'), ('Paused for 45 Minutes', 'Paused for 45 Minutes'), ('Paused for 1 hr', 'Paused for 1 hr')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Paused', 'Paused'), ('Paused for 15 Minutes', 'Paused for 15 Minutes'), ('Paused for 30 Minutes', 'Paused for 30 Minutes'), ('Paused for 45 Minutes', 'Paused for 45 Minutes'), ('Paused for 1 hr', 'Paused for 1 hr')], default='Open', max_length=50),
        ),
    ]
