# Generated by Django 2.1.5 on 2023-10-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_order_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
    ]
